# Generated by Django 5.0.6 on 2024-06-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donnees',
            old_name='capteurID',
            new_name='capteur',
        ),
        migrations.AlterField(
            model_name='capteurs',
            name='emplacement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='capteurs',
            name='piece',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
