# Generated by Django 5.0.6 on 2024-06-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0002_rename_capteurid_donnees_capteur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donnees',
            old_name='capteur',
            new_name='capteurID',
        ),
    ]
