# Generated by Django 5.0.6 on 2024-06-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0003_rename_capteur_donnees_capteurid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='capteurs',
            table='mqtt_capteurs',
        ),
        migrations.AlterModelTable(
            name='donnees',
            table='mqtt_donnees',
        ),
    ]
